### ISSUE TITLE
support for Flutter 3

### ISSUE THREAD

**Issue by daadu** [sharp3dges/animator#10]
```
../../.pub-cache/hosted/pub.dartlang.org/flutter_animator-3.2.1/lib/widgets/animator_widget.dart:102:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
```

build is breaking because of this lib

**Comment by daadu** [comment]
Oops, is not a build break but a "Warning".

**Comment by Adherentman** [comment]
use this
```
dependency_overrides:
  flutter_animator:
    git:
      url: https://github.com/Adherentman/animator.git
      ref: flutter3
```
